add_test( ArithmeticExpr.test_value_type /home/harry/Desktop/miniob_test/build/bin/arithmetic_expression_test [==[--gtest_filter=ArithmeticExpr.test_value_type]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArithmeticExpr.test_value_type PROPERTIES WORKING_DIRECTORY /home/harry/Desktop/miniob_test/build/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArithmeticExpr.test_try_get_value /home/harry/Desktop/miniob_test/build/bin/arithmetic_expression_test [==[--gtest_filter=ArithmeticExpr.test_try_get_value]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArithmeticExpr.test_try_get_value PROPERTIES WORKING_DIRECTORY /home/harry/Desktop/miniob_test/build/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( arithmetic_expression_test_TESTS ArithmeticExpr.test_value_type ArithmeticExpr.test_try_get_value)
