if(EXISTS "/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest/bitmap_test[1]_tests.cmake")
  include("/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest/bitmap_test[1]_tests.cmake")
else()
  add_test(bitmap_test_NOT_BUILT bitmap_test_NOT_BUILT)
endif()
