if(EXISTS "/home/someone/桌面/myd/miniob合并/sdk_miniob/build/unittest/record_manager_test[1]_tests.cmake")
  include("/home/someone/桌面/myd/miniob合并/sdk_miniob/build/unittest/record_manager_test[1]_tests.cmake")
else()
  add_test(record_manager_test_NOT_BUILT record_manager_test_NOT_BUILT)
endif()
