add_test( ring_buffer.test_init [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/bin/ring_buffer_test]==] [==[--gtest_filter=ring_buffer.test_init]==] --gtest_also_run_disabled_tests)
set_tests_properties( ring_buffer.test_init PROPERTIES WORKING_DIRECTORY [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ring_buffer.test_write [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/bin/ring_buffer_test]==] [==[--gtest_filter=ring_buffer.test_write]==] --gtest_also_run_disabled_tests)
set_tests_properties( ring_buffer.test_write PROPERTIES WORKING_DIRECTORY [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ring_buffer.test_read [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/bin/ring_buffer_test]==] [==[--gtest_filter=ring_buffer.test_read]==] --gtest_also_run_disabled_tests)
set_tests_properties( ring_buffer.test_read PROPERTIES WORKING_DIRECTORY [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ring_buffer.test_buffer [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/bin/ring_buffer_test]==] [==[--gtest_filter=ring_buffer.test_buffer]==] --gtest_also_run_disabled_tests)
set_tests_properties( ring_buffer.test_buffer PROPERTIES WORKING_DIRECTORY [==[/home/someone/桌面/myd/miniob-2023/sdk_miniob/build/unittest]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( ring_buffer_test_TESTS ring_buffer.test_init ring_buffer.test_write ring_buffer.test_read ring_buffer.test_buffer)
